apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hi-deployer
  namespace: default
spec:
  params:
    - default: deployer
      name: name
      type: string
  tasks:
    - name: hi
      params:
        - name: SCRIPT
          value: |-
            echo "$(params.name)"
      taskRef:
        kind: Task
        name: ibm-pak-0.2
