apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hi-deployer-
  namespace: default
spec:
  params:
    - name: name
      value: deployer-world
  pipelineRef:
    name: hi-deployer
  serviceAccountName: pipeline
  timeout: 8h0m0s
